In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.Weight = nn.Parameter(torch.ones(3))
    def forward(self, X,Y,Z):
        Y = X * Y
        O = Y * Z
        return O


In [45]:
import torch

A = 0.0001 * torch.arange(25).reshape(5, 5).float() - 25//2
B = 0.0001 * torch.arange(15).reshape(5, 3).float() - 25//2
bias = 0.0001 * torch.arange(3).float() - 25//2
A.requires_grad = True
B.requires_grad = True
bias.requires_grad = True
C = torch.matmul(A, B) + bias

C = torch.relu(C)
D = torch.matmul(A, C)
Y = torch.Tensor(
    [
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
    ]
)
loss = torch.nn.CrossEntropyLoss()(D, Y)
C_grad = None
def capture_grad(grad):
    global C_grad
    C_grad = grad
D.register_hook(capture_grad)

loss.backward()
# Attach hook
# torch.sum(C).backward()
# torch.sum(D).backward()
# Gradient of C using PyTorch
# grad_C = D.T @ A
# print("Gradient of C:\n", grad_C)

In [56]:
# torch.nn.Softmax()(D)
D

tensor([[-42472.8125, -42472.4570, -42472.1055],
        [-42471.0430, -42470.6914, -42470.3359],
        [-42469.2734, -42468.9219, -42468.5664],
        [-42467.5039, -42467.1523, -42466.7930],
        [-42465.7305, -42465.3789, -42465.0273]], grad_fn=<MmBackward0>)

In [47]:
C_grad

tensor([[ 0.0449, -0.1359,  0.0910],
        [ 0.0450, -0.1361,  0.0912],
        [ 0.0450, -0.1361,  0.0912],
        [ 0.0449, -0.1362,  0.0914],
        [ 0.0450, -0.1360,  0.0910]])

In [48]:
C_grad

tensor([[ 0.0449, -0.1359,  0.0910],
        [ 0.0450, -0.1361,  0.0912],
        [ 0.0450, -0.1361,  0.0912],
        [ 0.0449, -0.1362,  0.0914],
        [ 0.0450, -0.1360,  0.0910]])

In [49]:
A, B

(tensor([[-12.0000, -11.9999, -11.9998, -11.9997, -11.9996],
         [-11.9995, -11.9994, -11.9993, -11.9992, -11.9991],
         [-11.9990, -11.9989, -11.9988, -11.9987, -11.9986],
         [-11.9985, -11.9984, -11.9983, -11.9982, -11.9981],
         [-11.9980, -11.9979, -11.9978, -11.9977, -11.9976]],
        requires_grad=True),
 tensor([[-12.0000, -11.9999, -11.9998],
         [-11.9997, -11.9996, -11.9995],
         [-11.9994, -11.9993, -11.9992],
         [-11.9991, -11.9990, -11.9989],
         [-11.9988, -11.9987, -11.9986]], requires_grad=True))

In [50]:
A.grad, B.grad, bias.grad

(tensor([[-0.0006, -0.0006, -0.0006, -0.0006, -0.0006],
         [-0.0005, -0.0005, -0.0005, -0.0005, -0.0005],
         [-0.0005, -0.0005, -0.0005, -0.0005, -0.0005],
         [-0.0006, -0.0006, -0.0006, -0.0005, -0.0005],
         [-0.0006, -0.0006, -0.0005, -0.0005, -0.0005]]),
 tensor([[ 161.7550, -489.7880,  328.0330],
         [ 161.7536, -489.7839,  328.0303],
         [ 161.7523, -489.7798,  328.0276],
         [ 161.7509, -489.7758,  328.0249],
         [ 161.7496, -489.7717,  328.0221]]),
 tensor([-13.4807,  40.8191, -27.3384]))

In [15]:
import torch

A = 0.0001 * torch.arange(25).reshape(5, 5).float() - 25//2
B = 0.0001 * torch.arange(15).reshape(5, 3).float() - 25//2
A.requires_grad = True
B.requires_grad = True
C = torch.matmul(A, B)

C = torch.relu(C)
D = torch.matmul(A, C)

C_grad = None
def capture_grad(grad):
    global C_grad
    C_grad = grad

# Attach hook
C.register_hook(capture_grad)
# torch.sum(C).backward()
torch.sum(D).backward()
# Gradient of C using PyTorch
# grad_C = D.T @ A
# print("Gradient of C:\n", grad_C)

In [28]:
X = torch.Tensor([1, 2, 3])
Y = torch.Tensor([1, 2, 1])
Z = torch.Tensor([2, 4, 6])

N = torch.Tensor([3, 5, 7])
O = torch.Tensor([4, 6, 8])

X.requires_grad = True
Y.requires_grad = True
Z.requires_grad = True
N.requires_grad = True
O.requires_grad = True

O = X * Y * Z
Y = N * O

torch.sum(O).backward()

In [30]:
print("X",X, X.grad)
print("N",N, N.grad)
print("Z",Z, Z.grad)

X tensor([1., 2., 3.], requires_grad=True) tensor([2., 8., 6.])
N tensor([3., 5., 7.], requires_grad=True) None
Z tensor([2., 4., 6.], requires_grad=True) tensor([1., 4., 3.])


In [37]:
import torch
a = torch.randint(-5, 5, (1, 18)).float()
print(a)
print(torch.round(torch.nn.Softmax(dim = 1)(a)*1000)/1000)

tensor([[-5., -2., -1.,  3., -4., -5., -3.,  0., -2.,  0.,  1., -4., -1., -5.,
         -1.,  1., -2., -2.]])
tensor([[0.0000, 0.0050, 0.0130, 0.6860, 0.0010, 0.0000, 0.0020, 0.0340, 0.0050,
         0.0340, 0.0930, 0.0010, 0.0130, 0.0000, 0.0130, 0.0930, 0.0050, 0.0050]])


In [23]:
# Optimizers specified in the torch.optim package
# optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [12]:
import numpy as np

class Operation():
    def __init__(self, opcode, upstream, downstream):
        self.operation_type = opcode
        self.upstream = upstream
        self.downstream = downstream

    def forward(self, X):
        pass

    def backward(self):
        pass


SyntaxError: invalid syntax (2531931157.py, line 12)

In [3]:
class MatAdd(Operation):
    def __init__(self, upstream, downstream):
        super().__init__(MatAdd, upstream, downstream)
    
    def forward(self, X):
        np.matmul()


In [37]:
np.array([[1,2,3.],[1,2,3]])


array([[1., 2., 3.],
       [1., 2., 3.]])

In [56]:
x1 = np.array([[5,6,8]])
x2 = np.array([[6, 7, 4]])
np.vstack([x1, x2])
np.hstack([x1.T,x2.T])

array([[5, 6],
       [6, 7],
       [8, 4]])

In [49]:
np.ones((1,21))
np.zeros((3, 2))
np.arange(1, 4, 2)
np.linspace(1, 4, 5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [77]:
np.random.rand(1, 10) #0~1사이를 뽑아주는 애

array([[0.08187093, 0.8646923 , 0.5605796 , 0.20900085, 0.28125203,
        0.98691287, 0.26467386, 0.86587754, 0.30095717, 0.71690376]])

In [59]:
np.random.randn()   #가우시안 분포로 되어있는 애

1.6730294065870257

In [83]:
np.random.randn(3, 4) - 1

array([[-0.6287497 , -0.77123664, -1.43706051, -0.99526763],
       [-1.37702517, -0.45950201, -1.60865558, -0.74902435],
       [-1.63286084, -0.28308693, -1.4655558 , -1.22448358]])

In [95]:
np.array([[[[1,2],[3,4]]]]).squeeze().shape

(2, 2)